# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 07 Feb 2019 12:19:42 +0000
*               @ALL          1
*               @user         8
