<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Thu, 07 Feb 2019 12:19:42 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
